general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
}

# Bajar brillo a los 4 min
listener {
    timeout = 240
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# Bloquear a los 5 min
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# Apagar pantalla a los 5.5 min
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on
}
