# spotify-launcher: Spotify nativo en Wayland. Por Xwayland (con force_zero_scaling)
# se ve diminuto a escala 1.5.
[spotify]
extra_arguments = ["--enable-features=UseOzonePlatform,WaylandWindowDecorations", "--ozone-platform=wayland"]
